# Generated by Django 3.1.7 on 2021-10-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='showVideos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('videos', models.FileField(blank=True, default='', upload_to='videos_directory')),
                ('thumbnail', models.ImageField(default='', upload_to='Thumbnail')),
                ('title', models.CharField(default='', max_length=50)),
                ('channel_logo', models.ImageField(default='', upload_to='Channel_logo')),
                ('views', models.IntegerField(default='', max_length=10)),
                ('posted', models.DateTimeField()),
            ],
        ),
    ]
