# Generated by Django 3.1.7 on 2021-10-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_auto_20211007_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='showvideos',
            name='channel_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
