# Generated by Django 3.1.7 on 2021-10-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0006_auto_20211013_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='showvideos',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showvideos',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
