# Generated by Django 3.1.7 on 2021-10-18 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0007_auto_20211017_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showvideos',
            name='likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0)]),
        ),
    ]
