# Generated by Django 3.1.7 on 2021-10-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0008_auto_20211018_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showvideos',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
